apiVersion: apps/v1
kind: Deployment
metadata:
  name: Museum
  labels:
    app: Museum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Museum
  template:
    metadata:
      labels:
        app: Museum
    spec:
      containers:
        - name: Museum
          image: username/Museum:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5